drop table if exists Category;
drop table if exists Product;
create table Category (id integer not null, desciption varchar(255), name varchar(255), primary key (id)) type=MyISAM;
create table Product (id integer not null auto_increment, description varchar(255), name varchar(255), price bigint, quantity integer, catId integer, primary key (id)) type=MyISAM;
alter table Product add constraint FKd86ewaa07usmf7fh87enmako9 foreign key (catId) references Category (id);
drop table if exists Category;
drop table if exists Product;
create table Category (id integer not null, desciption varchar(255), name varchar(255), primary key (id)) type=MyISAM;
create table Product (id integer not null auto_increment, description varchar(255), name varchar(255), price bigint, quantity integer, catId integer, primary key (id)) type=MyISAM;
alter table Product add constraint FKd86ewaa07usmf7fh87enmako9 foreign key (catId) references Category (id);
drop table if exists Category;
drop table if exists Product;
create table Category (id integer not null, desciption varchar(255), name varchar(255), primary key (id)) type=MyISAM;
create table Product (id integer not null auto_increment, description varchar(255), name varchar(255), price bigint, quantity integer, catId integer, primary key (id)) type=MyISAM;
alter table Product add constraint FKd86ewaa07usmf7fh87enmako9 foreign key (catId) references Category (id);
drop table if exists Category;
drop table if exists Product;
create table Category (id integer not null, desciption varchar(255), name varchar(255), primary key (id)) type=MyISAM;
create table Product (id integer not null auto_increment, description varchar(255), name varchar(255), price bigint, quantity integer, catId integer, primary key (id)) type=MyISAM;
alter table Product add constraint FKd86ewaa07usmf7fh87enmako9 foreign key (catId) references Category (id);
drop table if exists Category;
drop table if exists Product;
create table Category (id integer not null, desciption varchar(255), name varchar(255), primary key (id)) type=MyISAM;
create table Product (id integer not null auto_increment, description varchar(255), name varchar(255), price bigint, quantity integer, catId integer, primary key (id)) type=MyISAM;
alter table Product add constraint FKd86ewaa07usmf7fh87enmako9 foreign key (catId) references Category (id);
drop table if exists Category;
drop table if exists Product;
create table Category (id integer not null, desciption varchar(255), name varchar(255), primary key (id)) type=MyISAM;
create table Product (id integer not null auto_increment, description varchar(255), name varchar(255), price bigint, quantity integer, catId integer, primary key (id)) type=MyISAM;
alter table Product add constraint FKd86ewaa07usmf7fh87enmako9 foreign key (catId) references Category (id);
drop table if exists Category;
drop table if exists Product;
create table Category (id integer not null, desciption varchar(255), name varchar(255), primary key (id)) type=MyISAM;
create table Product (id integer not null auto_increment, description varchar(255), name varchar(255), price bigint, quantity integer, catId integer, primary key (id)) type=MyISAM;
alter table Product add constraint FKd86ewaa07usmf7fh87enmako9 foreign key (catId) references Category (id);
drop table if exists Category;
drop table if exists Product;
create table Category (id integer not null, desciption varchar(255), name varchar(255), primary key (id)) type=MyISAM;
create table Product (id integer not null auto_increment, description varchar(255), name varchar(255), price bigint, quantity integer, catId integer, primary key (id)) type=MyISAM;
alter table Product add constraint FKd86ewaa07usmf7fh87enmako9 foreign key (catId) references Category (id);
alter table Product drop foreign key FKd86ewaa07usmf7fh87enmako9;
drop table if exists Category;
drop table if exists Product;
create table Category (id integer not null, desciption varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table Product (id integer not null auto_increment, description varchar(255), name varchar(255), price bigint, quantity integer, catId integer, primary key (id)) engine=InnoDB;
alter table Product add constraint FKd86ewaa07usmf7fh87enmako9 foreign key (catId) references Category (id);
alter table Product drop foreign key FKd86ewaa07usmf7fh87enmako9;
drop table if exists Category;
drop table if exists Product;
create table Category (id integer not null, desciption varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table Product (id integer not null auto_increment, description varchar(255), name varchar(255), price bigint, quantity integer, catId integer, primary key (id)) engine=InnoDB;
alter table Product add constraint FKd86ewaa07usmf7fh87enmako9 foreign key (catId) references Category (id);
alter table Product drop foreign key FKd86ewaa07usmf7fh87enmako9;
drop table if exists Category;
drop table if exists Product;
create table Category (id integer not null, desciption varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table Product (id integer not null auto_increment, description varchar(255), name varchar(255), price bigint, quantity integer, catId integer, primary key (id)) engine=InnoDB;
alter table Product add constraint FKd86ewaa07usmf7fh87enmako9 foreign key (catId) references Category (id);
drop table if exists Category;
drop table if exists Product;
create table Category (id integer not null, desciption varchar(255), name varchar(255), primary key (id)) type=MyISAM;
create table Product (id integer not null auto_increment, description varchar(255), name varchar(255), price bigint, quantity integer, catId integer, primary key (id)) type=MyISAM;
alter table Product add constraint FKd86ewaa07usmf7fh87enmako9 foreign key (catId) references Category (id);
drop table if exists Category;
drop table if exists Product;
create table Category (id integer not null, desciption varchar(255), name varchar(255), primary key (id)) type=MyISAM;
create table Product (id integer not null auto_increment, description varchar(255), name varchar(255), price bigint, quantity integer, catId integer, primary key (id)) type=MyISAM;
alter table Product add constraint FKd86ewaa07usmf7fh87enmako9 foreign key (catId) references Category (id);
drop table if exists Category;
drop table if exists Product;
create table Category (id integer not null, desciption varchar(255), name varchar(255), primary key (id)) type=MyISAM;
create table Product (id integer not null auto_increment, description varchar(255), name varchar(255), price bigint, quantity integer, catId integer, primary key (id)) type=MyISAM;
alter table Product add constraint FKd86ewaa07usmf7fh87enmako9 foreign key (catId) references Category (id);
